platform: linux/arm64

pipeline:
  docker:
    dockerfile: Dockerfile.aarch64
    image: plugins/docker:linux-arm64
    repo: yukimochi/alpine-vpnserver
    secrets: [ docker_username, docker_password ]
    tags: latest-aarch64
